name: CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: stable
      - name: Build
        run: make build
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Test
        run: make test
      - name: Update test coverage
        uses: ncruces/go-coverage-report@main
