name: CI

on: [ push, pull_request_target, workflow_dispatch ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: stable
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Build
        run: make build
      - name: Test
        run: make test
  release:
    name: Release
    needs: [ test ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'master'
    steps:
      - uses: actions/checkout@v3
      - name: Coverage
        uses: ncruces/go-coverage-report@main
      - name: Tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
